version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip uninstall -y awscli
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
  build:
    commands:
      - echo $AWS_REGION $AWS_ACCOUNT_ID $FUNCTION_NAME
      - aws --version
      - docker build . -t uach/ingress:latest
#     - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
#      - aws ecr create-repository --repository-name uach/ingress --image-scanning-configuration scanOnPush=true --image-tag-mutability MUTABLE
      - docker tag uach/ingress:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/uach/ingress:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/uach/ingress:latest
      - aws lambda create-function --function-name $FUNCTION_NAME --role arn:aws:iam::$AWS_ACCOUNT_ID:role/service-role/Test-role-teskqivt --code 'ImageUri=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/uach/ingress:latest' --package-type Image
